<?php

    

$B['GOOGLE_AUTHORIZATION'] = true; //false = Do not show buttons Login/Signup with Google | true = allow display buttons Login/Signup with Google

$C['IMAGE_FILE_MAX_SIZE'] = 5242880;  //Max size for image file in bytes | For example 5mb = 5*1024*1024

$C['ADMIN_ACCESS_LEVEL_ALL_RIGHTS'] = 0;
$C['ADMIN_ACCESS_LEVEL_READ_WRITE_RIGHTS'] = 1;
$C['ADMIN_ACCESS_LEVEL_MODERATOR_RIGHTS'] = 2;
$C['ADMIN_ACCESS_LEVEL_READ_ONLY_RIGHTS'] = 3;

$C['API_VERSION'] = "v2";

$C['APP_TYPE_ALL'] = -1;
$C['APP_TYPE_MANAGER'] = 0;
$C['APP_TYPE_WEB'] = 1;
$C['APP_TYPE_ANDROID'] = 2;
$C['APP_TYPE_IOS'] = 3;

$C['GCM_NOTIFY_MATCH'] = 25;

$C['GCM_NOTIFY_TYPING_START'] = 27;
$C['GCM_NOTIFY_TYPING_END'] = 28;

$C['GCM_NOTIFY_CHANGE_ACCOUNT_SETTINGS'] = 30;

$C['GCM_NOTIFY_PROFILE_NEW_MEDIA_ITEM_UPLOADED'] = 2003;

$C['NOTIFY_TYPE_MEDIA_APPROVE'] = 10;
$C['NOTIFY_TYPE_MEDIA_REJECT'] = 11;
$C['NOTIFY_TYPE_PROFILE_PHOTO_APPROVE'] = 12;
$C['NOTIFY_TYPE_PROFILE_PHOTO_REJECT'] = 13;
$C['NOTIFY_TYPE_ACCOUNT_APPROVE'] = 14;
$C['NOTIFY_TYPE_ACCOUNT_REJECT'] = 15;

$C['IMAGE_TYPE_PROFILE_PHOTO'] = 0;

$C['REPORT_TYPE_ITEM'] = 0;
$C['REPORT_TYPE_PROFILE'] = 1;
$C['REPORT_TYPE_MESSAGE'] = 2;
$C['REPORT_TYPE_GALLERY_ITEM'] = 4;
$C['REPORT_TYPE_MARKET_ITEM'] = 5;
$C['REPORT_TYPE_COMMUNITY'] = 6;

$C['ITEM_TYPE_IMAGE'] = 0;
$C['ITEM_TYPE_POST'] = 2;
$C['ITEM_TYPE_GALLERY'] = 4;

// Payments

// PA - PAYMENT ACTION
$C['PA_BUY_LEVEL'] = 0;

// PT - PAYMENT TYPE
$C['PT_UNKNOWN'] = 0;
$C['PT_CARD'] = 1;
$C['PT_GOOGLE_PURCHASE'] = 2;
$C['PT_APPLE_PURCHASE'] = 3;
$C['PT_BONUS'] = 4;

$C['CURRENCY_USD'] = 0;
$C['CURRENCY_EUR'] = 1;


$C['ERROR_FILE_SIZE_BIG'] = 501;
$C['ERROR_FILE_SIZE_SMALL'] = 502;

$C['ERROR_IMAGE_FILE_FORMAT'] = 503;
$C['ERROR_IMAGE_FILE_WIDTH_HEIGHT'] = 504;

$C['ERROR_OTP_VERIFICATION'] = 506;
$C['ERROR_OTP_PHONE_NUMBER_TAKEN'] = 507;

// Signin methods

$C['SIGNIN_EMAIL'] = 0;
$C['SIGNIN_OTP'] = 1;
$C['SIGNIN_FACEBOOK'] = 2;
$C['SIGNIN_GOOGLE'] = 3;
$C['SIGNIN_APPLE'] = 4;
$C['SIGNIN_TWITTER'] = 5;
$C['OAUTH_TYPE_GOOGLE'] = 1;